require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - run*.rb
    - tmp/**
    - bin/**
    - db/migrate/*
    - db/schema.rb

  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 500

Metrics/LineLength:
  Max: 150

Metrics/ParameterLists:
  Exclude:
    - 'app/concepts/**/operations/**'

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  EnforcedStyle: braces

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: aligned

Style/ParallelAssignment:
  Enabled: false
