# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.3'

# Infra stuffs
gem 'dotenv'
gem 'hashids'

# Rack stuffs
gem 'rack'
gem 'rack-cors'
gem 'rack-heartbeat'

# Trailblazer stuffs
gem 'slim'
gem 'trailblazer'
gem 'trailblazer-cells'
gem 'cells'
gem 'cells-slim'
gem 'reform'

# Database without Rails
gem 'activerecord'
gem 'pg'
gem 'sinatra-activerecord'

group :development, :test do
  gem 'factory_bot'
  gem 'faker'
  gem 'pry'
  gem 'pry-nav'
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'shotgun'
  gem 'simplecov'
  gem 'webmock'
end

group :test do
  gem 'database_cleaner'
end
